"""Support tools for the academic-reviewer and humanizer subagents.

Subagents are spawned by the main Claude via the Agent tool and receive no
session context. We pack everything a review pass needs into one MCP call
(`prepare_section_for_review`) so the subagent doesn't have to probe the DB.

The agents live in `.claude/agents/*.md` and are generated by `init_project`.
"""

import json
from typing import Any, Literal

from snowcite.app import mcp
from snowcite.artifacts import load_artifacts_by_ids
from snowcite.db import get_connection
from snowcite.persistence import load_papers_by_ids


type Reviewer = Literal["academic", "humanizer"]


@mcp.tool()
async def prepare_section_for_review(
    name: str,
    include_paper_abstracts: bool = True,
) -> dict[str, Any]:
    """Bundle everything a review subagent needs for one section.

    Returns the expanded content, the section's outline entry (target words,
    assigned paper IDs), the assigned papers with abstracts (for claim /
    citation verification), and a lightweight view of neighbouring sections
    (names only) so the reviewer can spot cross-section duplication.

    Set `include_paper_abstracts=False` to skip abstract bodies when the
    section cites many papers and the reviewer just needs the title/DOI.
    """
    async with get_connection() as conn:
        cur = await conn.execute(
            "SELECT name, content, word_count, version, polished, updated_at "
            "FROM section_content WHERE name = ?",
            (name,),
        )
        section_row = await cur.fetchone()
        if section_row is None:
            return {"error": f"section {name!r} not found"}
        section = {k: section_row[k] for k in section_row.keys()}

        cur = await conn.execute("SELECT sections_json FROM outline WHERE id = 1")
        outline_row = await cur.fetchone()
        outline_entry: dict[str, Any] | None = None
        assigned_paper_ids: list[int] = []
        assigned_artifact_ids: list[int] = []
        if outline_row:
            outline_sections = json.loads(outline_row["sections_json"])
            outline_entry = next((s for s in outline_sections if s.get("name") == name), None)
            if outline_entry:
                assigned_paper_ids = outline_entry.get("paper_ids") or []
                assigned_artifact_ids = outline_entry.get("artifact_ids") or []

        cur = await conn.execute(
            "SELECT name FROM section_content WHERE name != ? ORDER BY name",
            (name,),
        )
        other_sections = [r["name"] for r in await cur.fetchall()]

        cur = await conn.execute(
            "SELECT language, standard, discipline, review_strictness, backend "
            "FROM project_metadata WHERE id = 1"
        )
        meta_row = await cur.fetchone()
        project_context = (
            {k: meta_row[k] for k in meta_row.keys() if meta_row[k] is not None} if meta_row else {}
        )

    assigned_papers = await load_papers_by_ids(assigned_paper_ids)
    if not include_paper_abstracts:
        for p in assigned_papers:
            p.pop("abstract", None)

    # Artifacts — full content, since the reviewer may need to verify quotes
    # character-by-character against transcripts or code.
    assigned_artifacts = [
        dict(a) for a in await load_artifacts_by_ids(assigned_artifact_ids) if a["included"]
    ]

    return {
        "section": section,
        "outline_entry": outline_entry,
        "assigned_papers": assigned_papers,
        "assigned_artifacts": assigned_artifacts,
        "other_sections": other_sections,
        "project_context": project_context,
    }
